// Auto-generated bridge routes mapping
// This file maps each chain ID to all chains reachable via OFT and Across tokens
// Generated on: 2025-10-03T11:09:25.586Z

import { ExtendedSupportedChainId, UISupportedChainId } from 'constants/chainInfo'
import { SupportedChainId } from 'maia-core-sdk'

export interface BridgeRoutesMapping {
  [chainId: number]: UISupportedChainId[];
}

/**
 * BRIDGE_ROUTES mapping showing all chains reachable from each chain
 * via OFT (Omnichain Fungible Tokens) and Across protocol tokens
 * 
 * Key: Source chain ID (UISupportedChainId)
 * Value: Array of reachable destination chain IDs (as UISupportedChainId[])
 * 
 * Note: Only includes tokens with liquidity (noLiquidityOnChain !== true)
 */

export const BRIDGE_ROUTES: BridgeRoutesMapping = {
  [SupportedChainId.MAINNET]: [SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.OPBNB, ExtendedSupportedChainId.TAC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.SANKO, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.PEAQ, ExtendedSupportedChainId.MANTLE, ExtendedSupportedChainId.NIBIRU, SupportedChainId.BASE, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.TAIKO, ExtendedSupportedChainId.BITLAYER, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.KATANA, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.OPTIMISM]: [SupportedChainId.MAINNET, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.TAIKO, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.FLARE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.ROOTSTOCK, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, SupportedChainId.BERA],
  [ExtendedSupportedChainId.ROOTSTOCK]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, SupportedChainId.BERA],
  [SupportedChainId.BSC]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.ROOTSTOCK, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.OPBNB, ExtendedSupportedChainId.TAC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.COREDAO, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.GOAT, ExtendedSupportedChainId.PEAQ, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.TAIKO, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.KATANA, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.UNICHAIN]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.OPBNB, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.POLYGON]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.SONIC]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, SupportedChainId.POLYGON, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST],
  [ExtendedSupportedChainId.MANTA]: [SupportedChainId.MAINNET, SupportedChainId.METIS, ExtendedSupportedChainId.MANTLE, ExtendedSupportedChainId.MODE, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.SCROLL],
  [ExtendedSupportedChainId.TAC]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, SupportedChainId.BERA, ExtendedSupportedChainId.SCROLL],
  [SupportedChainId.FRAXTAL]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.KATANA],
  [ExtendedSupportedChainId.ORDERLY]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.OPBNB, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.WORLDCHAIN]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.FLOW]: [SupportedChainId.MAINNET, ExtendedSupportedChainId.SEI, SupportedChainId.BASE, ExtendedSupportedChainId.APE, SupportedChainId.AVAX, ExtendedSupportedChainId.LINEA],
  [ExtendedSupportedChainId.HYPERLIQUID]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, ExtendedSupportedChainId.XDC, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.OPBNB, ExtendedSupportedChainId.TAC, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.METIS]: [SupportedChainId.MAINNET],
  [ExtendedSupportedChainId.SEI]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.BOB, SupportedChainId.BERA],
  [ExtendedSupportedChainId.SONEIUM]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.TAC, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, SupportedChainId.SWELL, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.SWELL]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.OPBNB, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.SANKO]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, SupportedChainId.POLYGON, ExtendedSupportedChainId.OPBNB, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.SUPERPOSITION, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.GOAT]: [SupportedChainId.BSC],
  [ExtendedSupportedChainId.MORPH]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, SupportedChainId.SWELL, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.TAIKO, ExtendedSupportedChainId.SCROLL],
  [ExtendedSupportedChainId.PEAQ]: [SupportedChainId.MAINNET, SupportedChainId.BSC, SupportedChainId.BASE],
  [ExtendedSupportedChainId.MANTLE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL],
  [ExtendedSupportedChainId.NIBIRU]: [SupportedChainId.MAINNET, SupportedChainId.BSC, SupportedChainId.POLYGON, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.BERA],
  [SupportedChainId.BASE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.XDC, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.TAC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.PEAQ, ExtendedSupportedChainId.MANTLE, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.APE]: [SupportedChainId.MAINNET, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.BERA],
  [ExtendedSupportedChainId.MODE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.ARBITRUM_ONE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.OPBNB, ExtendedSupportedChainId.TAC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.SANKO, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, ExtendedSupportedChainId.CELO, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.CELO]: [SupportedChainId.MAINNET, SupportedChainId.ARBITRUM_ONE],
  [SupportedChainId.AVAX]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.KATANA],
  [ExtendedSupportedChainId.SUPERPOSITION]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, SupportedChainId.POLYGON, ExtendedSupportedChainId.OPBNB, ExtendedSupportedChainId.SANKO, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.TAIKO, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.INK]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, SupportedChainId.AVAX, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.LINEA]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, SupportedChainId.METIS, ExtendedSupportedChainId.SONEIUM, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.BOB]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.OPBNB, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.BERA]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.SCROLL],
  [ExtendedSupportedChainId.BLAST]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, SupportedChainId.METIS, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.PLUMEPHOENIX]: [SupportedChainId.MAINNET, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.SONIC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.COREDAO, ExtendedSupportedChainId.SEI, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, SupportedChainId.BERA],
  [ExtendedSupportedChainId.BITLAYER]: [SupportedChainId.MAINNET, SupportedChainId.BSC],
  [ExtendedSupportedChainId.SCROLL]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.KATANA]: [SupportedChainId.MAINNET],
  [ExtendedSupportedChainId.ZORA]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL]
} as const;

/**
 * Helper function to get all chains reachable from a given chain ID
 * @param fromChainId - The source chain ID
 * @returns Array of reachable chain IDs
 */
export function getReachableChains(fromChainId: UISupportedChainId): UISupportedChainId[] {
  return BRIDGE_ROUTES[fromChainId] || [];
}

/**
 * Helper function to check if two chains are connected via bridge
 * @param fromChainId - The source chain ID
 * @param toChainId - The destination chain ID
 * @returns Boolean indicating if the chains are connected
 */
export function canBridge(fromChainId: UISupportedChainId, toChainId: UISupportedChainId): boolean {
  const reachableChains = BRIDGE_ROUTES[fromChainId] || [];
  return reachableChains.includes(toChainId);
}

/**
 * Helper function to get all unique chain IDs that have bridge routes
 * @returns Array of all chain IDs with bridge capabilities
 */
export function getAllBridgeChains(): UISupportedChainId[] {
  return Object.keys(BRIDGE_ROUTES)
    .map(Number)
    .filter((id): id is UISupportedChainId => !isNaN(id));
}
