// Auto-generated bridge routes mapping
// This file maps each chain ID to all chains reachable via OFT and Across tokens
// Generated on: 2025-12-01T18:03:12.662Z

import { ExtendedSupportedChainId, UISupportedChainId } from 'constants/chainInfo'
import { SupportedChainId } from 'maia-core-sdk'

interface BridgeRoutesMapping {
  [chainId: number]: UISupportedChainId[];
}

/**
 * BRIDGE_ROUTES mapping showing all chains reachable from each chain
 * via OFT (Omnichain Fungible Tokens) and Across protocol tokens
 * 
 * Key: Source chain ID (UISupportedChainId)
 * Value: Array of reachable destination chain IDs (as UISupportedChainId[])
 * 
 * Note: Only includes tokens with liquidity (noLiquidityOnChain !== true)
 */

const BRIDGE_ROUTES: BridgeRoutesMapping = {
  [SupportedChainId.MAINNET]: [SupportedChainId.OPTIMISM, ExtendedSupportedChainId.XDC, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.TAC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.SANKO, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.PEAQ, ExtendedSupportedChainId.MANTLE, ExtendedSupportedChainId.NIBIRU, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.CELO, ExtendedSupportedChainId.HEMI, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.TAIKO, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ETHEREAL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.OPTIMISM]: [SupportedChainId.MAINNET, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.GNOSIS, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.TAIKO, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.FLARE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.ROOTSTOCK, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.MANTLE, ExtendedSupportedChainId.PLASMA, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, SupportedChainId.BERA],
  [ExtendedSupportedChainId.ROOTSTOCK]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, SupportedChainId.BERA],
  [SupportedChainId.BSC]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.ROOTSTOCK, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.TAC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.COREDAO, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.PEAQ, ExtendedSupportedChainId.MANTLE, ExtendedSupportedChainId.NIBIRU, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.HEMI, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.TAIKO, ExtendedSupportedChainId.BITLAYER, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.UNICHAIN]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, SupportedChainId.POLYGON, SupportedChainId.SONIC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.POLYGON]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, ExtendedSupportedChainId.MONAD, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.MONAD]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, SupportedChainId.BSC, SupportedChainId.POLYGON, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.APE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, SupportedChainId.BERA],
  [SupportedChainId.SONIC]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.BOB, SupportedChainId.BERA],
  [ExtendedSupportedChainId.TAC]: [SupportedChainId.MAINNET, SupportedChainId.BSC, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.BERA],
  [SupportedChainId.FRAXTAL]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.KATANA],
  [ExtendedSupportedChainId.ORDERLY]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, SupportedChainId.POLYGON, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX],
  [ExtendedSupportedChainId.WORLDCHAIN]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.FLOW]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.SONIC, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, SupportedChainId.BASE, SupportedChainId.AVAX, ExtendedSupportedChainId.BOB, SupportedChainId.BERA],
  [ExtendedSupportedChainId.HYPERLIQUID]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.APE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, SupportedChainId.BERA],
  [SupportedChainId.METIS]: [SupportedChainId.MAINNET],
  [ExtendedSupportedChainId.SEI]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.SONIC, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.BOB, SupportedChainId.BERA],
  [ExtendedSupportedChainId.SONEIUM]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.SONIC, ExtendedSupportedChainId.TAC, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, SupportedChainId.SWELL, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.SWELL]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.SANKO]: [SupportedChainId.MAINNET, ExtendedSupportedChainId.APE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.SUPERPOSITION],
  [ExtendedSupportedChainId.MORPH]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, SupportedChainId.METIS, SupportedChainId.SWELL, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL],
  [ExtendedSupportedChainId.PEAQ]: [SupportedChainId.MAINNET, SupportedChainId.BSC, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE],
  [ExtendedSupportedChainId.MANTLE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL],
  [ExtendedSupportedChainId.NIBIRU]: [SupportedChainId.MAINNET, SupportedChainId.BSC, SupportedChainId.POLYGON, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, SupportedChainId.BERA],
  [SupportedChainId.BASE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, ExtendedSupportedChainId.TAC, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.PEAQ, ExtendedSupportedChainId.MANTLE, ExtendedSupportedChainId.NIBIRU, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.PLASMA]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, SupportedChainId.BERA],
  [ExtendedSupportedChainId.APE]: [SupportedChainId.MAINNET, SupportedChainId.BSC, ExtendedSupportedChainId.MONAD, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.ARBITRUM_ONE],
  [ExtendedSupportedChainId.MODE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [SupportedChainId.ARBITRUM_ONE]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.SONIC, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.ORDERLY, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.SANKO, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.PEAQ, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.APE, ExtendedSupportedChainId.MODE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.PLUMEPHOENIX, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ETHEREAL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.CELO]: [SupportedChainId.MAINNET, SupportedChainId.ARBITRUM_ONE],
  [ExtendedSupportedChainId.HEMI]: [SupportedChainId.MAINNET, SupportedChainId.BSC, ExtendedSupportedChainId.INK],
  [SupportedChainId.AVAX]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.SONIC, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, SupportedChainId.METIS, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST],
  [ExtendedSupportedChainId.SUPERPOSITION]: [ExtendedSupportedChainId.SANKO, SupportedChainId.ARBITRUM_ONE],
  [ExtendedSupportedChainId.INK]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.LINEA]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.BOB]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.SONIC, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, SupportedChainId.BASE, SupportedChainId.AVAX, SupportedChainId.BERA],
  [SupportedChainId.BERA]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, ExtendedSupportedChainId.FLARE, ExtendedSupportedChainId.ROOTSTOCK, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MONAD, SupportedChainId.SONIC, ExtendedSupportedChainId.FLOW, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SEI, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.PLASMA, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BOB, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL],
  [ExtendedSupportedChainId.BLAST]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.MANTA, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.WORLDCHAIN, SupportedChainId.METIS, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, ExtendedSupportedChainId.MANTLE, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.SCROLL, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.PLUMEPHOENIX]: [SupportedChainId.MAINNET, SupportedChainId.BSC, SupportedChainId.POLYGON, SupportedChainId.FRAXTAL, ExtendedSupportedChainId.SEI, SupportedChainId.BASE, SupportedChainId.ARBITRUM_ONE, SupportedChainId.AVAX, ExtendedSupportedChainId.INK],
  [ExtendedSupportedChainId.BITLAYER]: [SupportedChainId.MAINNET, SupportedChainId.BSC],
  [ExtendedSupportedChainId.SCROLL]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.HYPERLIQUID, ExtendedSupportedChainId.SONEIUM, SupportedChainId.SWELL, ExtendedSupportedChainId.MORPH, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, SupportedChainId.BERA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.ZORA],
  [ExtendedSupportedChainId.KATANA]: [SupportedChainId.FRAXTAL],
  [ExtendedSupportedChainId.ETHEREAL]: [SupportedChainId.MAINNET, SupportedChainId.ARBITRUM_ONE],
  [ExtendedSupportedChainId.ZORA]: [SupportedChainId.MAINNET, SupportedChainId.OPTIMISM, SupportedChainId.BSC, ExtendedSupportedChainId.UNICHAIN, SupportedChainId.POLYGON, ExtendedSupportedChainId.WORLDCHAIN, ExtendedSupportedChainId.SONEIUM, SupportedChainId.BASE, ExtendedSupportedChainId.MODE, SupportedChainId.ARBITRUM_ONE, ExtendedSupportedChainId.INK, ExtendedSupportedChainId.LINEA, ExtendedSupportedChainId.BLAST, ExtendedSupportedChainId.SCROLL]
} as const;

/**
 * Helper function to get all chains reachable from a given chain ID
 * @param fromChainId - The source chain ID
 * @returns Array of reachable chain IDs
 */
export function getReachableChains(fromChainId: UISupportedChainId): UISupportedChainId[] {
  return BRIDGE_ROUTES[fromChainId] || [];
}
